Yes, this is an org file. I use Emacs.

** Please consider contributing!
During development of this update, I am /very/ open to contributions!
See the ~CONTRIBUTING.md~ for more info. :-3

* Lifeline.PYR v1.2 Development
This file is for me to organise what I (and possibly contributers) should
prioritise working on, and to list (and publish) what I'm planning.

** Playability Status
Working!

** Gameplay features for Lifeline.PYR [0/2]
- [ ] Cheats
- [ ] New gamemode (unnamed, though planned)

** Smaller changes [0/1]

** Bugs to fix [0/0]
*Note:* If you find any bugs, /please/ make a GitHub Issue, Discussion, or
contact me about it (see _Contact_ header @ https://jasperredis.net)!

Currently no known bugs!

** General goals to work towards
- Refactor old and bad code
- Make bad systems better, more extensible, more practical, etc.
- Adhere to style guides and conventions
- Remove unneccessary comments
- Make the game look overall better

* Changes so Far
If you're coming here for gameplay updates, note that this is a mix of both
technical changes and updates!
- Large refactors in gameplay involving splitting "mega-functions" into smaller
  functions. Also included slight improvements to many functions.
- Split gameplay and game mode selection into separate stages.
